export const metadata = {
  "version": "3.0",
  "token_endpoint_auth_methods_supported": [
    "client_secret_post",
    "client_secret_basic",
    "client_secret_jwt",
    "private_key_jwt"
  ],
  "claims_parameter_supported": true,
  "request_parameter_supported": true,
  "request_uri_parameter_supported": true,
  "require_request_uri_registration": false,
  "grant_types_supported": [
    "authorization_code",
    "implicit",
    "urn:ietf:params:oauth:grant-type:jwt-bearer",
    "refresh_token"
  ],
  "frontchannel_logout_supported": false,
  "frontchannel_logout_session_supported": false,
  "backchannel_logout_supported": false,
  "backchannel_logout_session_supported": false,
  "response_types_supported": [
    "code",
    "token",
    "id_token",
    "code token",
    "code id_token",
    "id_token token",
    "code token id_token",
    "none"
  ],
  "response_modes_supported": [
    "query",
    "fragment",
    "form_post"
  ],
  "subject_types_supported": [
    "public",
    "pairwise"
  ],
  "claim_types_supported": [
    "normal",
    "aggregated",
    "distributed"
  ],
  "scopes_supported": [
    "offline_access",
    "openid",
    "address",
    "email",
    "phone",
    "openid2",
    "profile"
  ],
  "token_endpoint_auth_signing_alg_values_supported": [
    "RS256",
    "RS384",
    "RS512",
    "ES256",
    "ES384",
    "ES512",
    "HS256",
    "HS384",
    "HS512",
    "PS256",
    "PS384",
    "PS512"
  ],
  "revocation_endpoint_auth_signing_alg_values_supported": [
    "RS256",
    "RS384",
    "RS512",
    "ES256",
    "ES384",
    "ES512",
    "HS256",
    "HS384",
    "HS512",
    "PS256",
    "PS384",
    "PS512"
  ],
  "revocation_endpoint_auth_methods_supported": [
    "client_secret_post",
    "client_secret_basic",
    "client_secret_jwt",
    "private_key_jwt"
  ],
  "introspection_endpoint_auth_signing_alg_values_supported": [
    "RS256",
    "RS384",
    "RS512",
    "ES256",
    "ES384",
    "ES512",
    "HS256",
    "HS384",
    "HS512",
    "PS256",
    "PS384",
    "PS512"
  ],
  "introspection_endpoint_auth_methods_supported": [
    "client_secret_post",
    "client_secret_basic",
    "client_secret_jwt",
    "private_key_jwt"
  ],
  "claims_supported": [
    "mojeid_address_def",
    "mojeid_address_ship_street3",
    "mojeid_address_ship3_street2",
    "mojeid_address_bill_street2",
    "mojeid_address_ship3",
    "mojeid_address_bill_country",
    "mojeid_url_instagram",
    "mojeid_address_def_street",
    "picture",
    "mojeid_address_ship3_city",
    "mojeid_url_tumblr",
    "mojeid_ident_card",
    "given_name",
    "mojeid_email_notify",
    "mojeid_address_bill_street",
    "mojeid_address_ship2_postal_code",
    "mojeid_phone_mobile",
    "mojeid_url_gravatar",
    "mojeid_address_ship2_company_name",
    "mojeid_address_ship_street",
    "mojeid_address_def_state",
    "mojeid_nia",
    "email",
    "mojeid_valid",
    "mojeid_address_ship",
    "sub",
    "mojeid_address_ship2_country",
    "mojeid_isic",
    "mojeid_address_ship_postal_code",
    "mojeid_address_mail_street3",
    "nickname",
    "mojeid_ident_ssn",
    "mojeid_public_pgp",
    "family_name",
    "mojeid_url_office",
    "zoneinfo",
    "mojeid_isds",
    "mojeid_address_def_country",
    "mojeid_address_def_postal_code",
    "mojeid_address_bill_city",
    "mojeid_address_ship2_state",
    "openid2_id",
    "mojeid_address_ship_street2",
    "mojeid_student",
    "mojeid_url_about_me",
    "mojeid_url_twiter",
    "mojeid_address_ship_country",
    "mojeid_address_def_city",
    "mojeid_phone_home",
    "middle_name",
    "locale",
    "mojeid_url_facebook",
    "email_verified",
    "mojeid_url_blog",
    "name",
    "mojeid_address_bill",
    "mojeid_address_ship_city",
    "mojeid_url_flickr",
    "mojeid_age",
    "mojeid_address_mail_street",
    "mojeid_url_blogger",
    "mojeid_address_mail_street2",
    "mojeid_url_linkedin",
    "mojeid_is_adult",
    "mojeid_address_bill_street3",
    "updated_at",
    "mojeid_address_bill_state",
    "mojeid_url_pinterest",
    "mojeid_address_ship3_country",
    "address",
    "mojeid_address_ship3_street",
    "mojeid_ident_vat",
    "mojeid_address_bill_postal_code",
    "mojeid_address_mail_state",
    "mojeid_bank_account_iban",
    "mojeid_address_ship3_state",
    "mojeid_address_ship_state",
    "mojeid_email_next",
    "mojeid_im_windows_live",
    "mojeid_im_skype",
    "mojeid_address_ship3_company_name",
    "mojeid_address_def_street2",
    "profile",
    "gender",
    "birthdate",
    "mojeid_address_ship2_street2",
    "website",
    "preferred_username",
    "mojeid_address_mail_verified",
    "mojeid_ident_pass",
    "mojeid_address_ship2_street",
    "mojeid_vat",
    "mojeid_address_ship2_street3",
    "mojeid_address_mail_postal_code",
    "mojeid_address_ship_company_name",
    "mojeid_url_rss",
    "mojeid_address_def_street3",
    "mojeid_url_wordpress",
    "mojeid_address_mail_city",
    "mojeid_phone_office",
    "mojeid_phone_fax",
    "mojeid_bank_account",
    "mojeid_im_jabber",
    "phone_number",
    "mojeid_url_youtube",
    "mojeid_address_mail_country",
    "mojeid_url_vimeo",
    "mojeid_address_ship3_postal_code",
    "phone_number_verified",
    "mojeid_url_foursquare",
    "mojeid_address_ship2_city",
    "mojeid_im_google_talk",
    "mojeid_address_ship3_street3",
    "mojeid_address_ship2",
    "mojeid_im_icq",
    "mojeid_nia_substantial_pseudonym",
    "mojeid_organization",
    "mojeid_username"
  ],
  "userinfo_signing_alg_values_supported": [
    "RS256",
    "RS384",
    "RS512",
    "ES256",
    "ES384",
    "ES512",
    "HS256",
    "HS384",
    "HS512",
    "PS256",
    "PS384",
    "PS512",
    "none"
  ],
  "id_token_signing_alg_values_supported": [
    "RS256",
    "RS384",
    "RS512",
    "ES256",
    "ES384",
    "ES512",
    "HS256",
    "HS384",
    "HS512",
    "PS256",
    "PS384",
    "PS512",
    "none"
  ],
  "request_object_signing_alg_values_supported": [
    "RS256",
    "RS384",
    "RS512",
    "ES256",
    "ES384",
    "ES512",
    "HS256",
    "HS384",
    "HS512",
    "PS256",
    "PS384",
    "PS512",
    "none"
  ],
  "userinfo_encryption_alg_values_supported": [
    "RSA1_5",
    "RSA-OAEP",
    "RSA-OAEP-256",
    "A128KW",
    "A192KW",
    "A256KW",
    "ECDH-ES",
    "ECDH-ES+A128KW",
    "ECDH-ES+A192KW",
    "ECDH-ES+A256KW"
  ],
  "id_token_encryption_alg_values_supported": [
    "RSA1_5",
    "RSA-OAEP",
    "RSA-OAEP-256",
    "A128KW",
    "A192KW",
    "A256KW",
    "ECDH-ES",
    "ECDH-ES+A128KW",
    "ECDH-ES+A192KW",
    "ECDH-ES+A256KW"
  ],
  "request_object_encryption_alg_values_supported": [
    "RSA1_5",
    "RSA-OAEP",
    "RSA-OAEP-256",
    "A128KW",
    "A192KW",
    "A256KW",
    "ECDH-ES",
    "ECDH-ES+A128KW",
    "ECDH-ES+A192KW",
    "ECDH-ES+A256KW"
  ],
  "userinfo_encryption_enc_values_supported": [
    "A128CBC-HS256",
    "A192CBC-HS384",
    "A256CBC-HS512",
    "A128GCM",
    "A192GCM",
    "A256GCM"
  ],
  "id_token_encryption_enc_values_supported": [
    "A128CBC-HS256",
    "A192CBC-HS384",
    "A256CBC-HS512",
    "A128GCM",
    "A192GCM",
    "A256GCM"
  ],
  "request_object_encryption_enc_values_supported": [
    "A128CBC-HS256",
    "A192CBC-HS384",
    "A256CBC-HS512",
    "A128GCM",
    "A192GCM",
    "A256GCM"
  ],
  "acr_values_supported": [
    "",
    "pwd",
    "mod-pr",
    "phr",
    "http://eidas.europa.eu/LoA/substantial",
    "http://eidas.europa.eu/LoA/high"
  ],
  "issuer": "https://mojeid.cz/oidc/",
  "jwks_uri": "https://mojeid.cz/oidc/key.jwk",
  "authorization_endpoint": "https://mojeid.cz/oidc/authorization/",
  "registration_endpoint": "https://mojeid.cz/oidc/registration/",
  "token_endpoint": "https://mojeid.cz/oidc/token/",
  "userinfo_endpoint": "https://mojeid.cz/oidc/userinfo/"
}

export const jwks = {
  "keys": [
    {
      "n": "l9_1jQA9gWH8mXhf9AyD7ijU19DubIEkeO99eGsENEex3pUYjjMp0bdjakyODyWe4CrlAAGQqB-r3i2GfwhEBJ4jZ0a4MI9jqFysAgzLB0OILRhHCIW1DImQIk2o4dQOQqyKorVBlxwv7-VP7eeqs-EopZnhINiOFB7nRB8txslqj-tM1yaAy6kxYbn8qe9LwRBZtx8o5DkSmK1tFiOLk-kOkaw1XJfRI-B35Rgw_UwLZ4b_CxpWS7g8HIGgU9Ht8FJdnuWWgY1W8xlxoyWDhT8RA0sNRD0DlQcx6hzDwmrI25fubzBTbCd3vFwjBQbObDmWfoY6C5mi08dvg6avSzMEtu0-I-S1750AgfAFpi9uHsCknjSiyIQcSWRam6TrEnKXkkqxL519h5Uo15aQ8pvJn7i29xMRQM5TV5LKJvDlazrWzmDpSlD7Bab083o3FovyHaG9zoff5i7XBXN93PNikCihHZeBUzBcATz_lLFrX-YE1_IIKIL98v7sJiGQiBgnK8YCZwB75Vutsf6tkDwOpxAMirOgazJNbTTqfvZjDh1pbPMFF29QX2h9027HD0pPVo92orCnPYYtWrFQ8bQv8-gZ0GyhkqaWwP3-4aAZ4Q5Bd5_DWJWUK4GG5NBh3msu8MhjE4caR2zmsHN4nf0INsfJFqGmDBRBg-GMO0s",
      "e": "AQAB",
      "kty": "RSA",
      "kid": "Pt7HjUz1rqdn1ae1ezT-nO5Fwp6CwuJU5OVaXQJ3uPg"
    }
  ]
}
