name: Update

on:
  pull_request:
    branches: [main]
    types: [auto_merge_enabled]

jobs:
  get-issuers:
    name: Get Issuers
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'npm'

      - name: NPM Release
        run: npm release --dry-run
