name: Release

on:
  push:
    branches:
      - 'main'
    paths:
      - 'issuers/**'

jobs:
  release:
    name: NPM Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: get path
        id: get-path
        run: |
          path=$(git diff-tree --no-commit-id --name-only -r HEAD | awk -F'/' 'NF>1 {OFS="/"; $NF=""; sub(/\/$/, ""); print $0}' | grep -v '^$' | sort | uniq)
          echo "path=$(echo $path)" >> "$GITHUB_OUTPUT"
      - name: npm release
        working-directory: ${{ steps.get-path.outputs.path }}
        run: |
          npm publish --dry-run
