name: Update

on:
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    outputs:
      updated: ${{ steps.collect.outputs.updated }}
      cache-key: ${{ steps.collect.outputs.cache-key }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run update script
        run: node update.mjs

      - name: Collect updated directories
        id: collect
        run: |
            directories=$(git diff --name-only --staged | xargs -n1 dirname | sort -u)
            json=$(echo "$directories" | jq -R . | jq -s 'map(select(length > 0))')
            echo "updated=$(echo "$json" | jq -c)" >> "$GITHUB_OUTPUT"
            echo "cache-key=issuers-${{ hashFiles('issuers/**/*') }}" >> $GITHUB_OUTPUT

      - name: Cache updates
        uses: actions/cache@v4
        with:
          path: issuers
          key: ${{ steps.collect.outputs.cache-key }}

      - run: git status

  prs:
    name: Update ${{ matrix.dir }}
    runs-on: ubuntu-latest
    needs: update
    strategy:
      matrix:
        dir: ${{ fromJSON(needs.update.outputs.updated) }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Load cached updates
        uses: actions/cache@v4
        with:
          path: issuers
          key: ${{ needs.update.outputs.cache-key }}
          fail-on-cache-miss: true

      - run: git status

      - uses: gr2m/create-or-update-pull-request-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          path: ${{ matrix.dir }}
